---
abstract: 'Test::WWW::Mechanize for Mojo / Mojolicious'
author:
  - 'Ash Berlin C<< <ash@cpan.org> >> (current maintiner)'
  - 'Original Author: Leon Brocard, C<< <acme@astray.com> >>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Mechanize-Mojo
provides:
  Test::WWW::Mechanize::Mojo:
    file: lib/Test/WWW/Mechanize/Mojo.pm
    version: v0.0.1
requires:
  LWP: 5.816
  Mojolicious::Lite: 0
  Test::WWW::Mechanize: 1.14
  WWW::Mechanize: 1.50
  namespace::clean: 0.09
resources:
  homepage: http://web-cpan.berlios.de/modules/Test-WWW-Mechanize-Mojo/
  license: http://dev.perl.org/licenses/
  repository: http://svn.berlios.de/svnroot/repos/web-cpan/Test-WWW-Mechanize-Mojo
version: v0.0.1
