---
abstract: 'Test::WWW::Mechanize for Mojo / Mojolicious'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Mechanize-Mojo
provides:
  Test::WWW::Mechanize::Mojo:
    file: lib/Test/WWW/Mechanize/Mojo.pm
    version: v0.0.11
requires:
  Carp: 0
  Encode: 0
  HTML::Entities: 0
  LWP: 5.816
  Mojolicious: 1.01
  Mojolicious::Lite: 0
  Test::WWW::Mechanize: 1.14
  WWW::Mechanize: 1.50
  base: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  homepage: http://web-cpan.berlios.de/modules/Test-WWW-Mechanize-Mojo/
  license: http://dev.perl.org/licenses/
  repository: http://svn.berlios.de/svnroot/repos/web-cpan/Test-WWW-Mechanize-Mojo
version: v0.0.11
